# Generated by Django 4.1.5 on 2023-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0002_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
